project:
  type: website
  resources: 
    - "Website_Res.pdf"

website:
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: research.qmd
        text: Research

  page-footer:
    right: "&copy; 2026, Djovan Velasco"

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

execute: 
  freeze: auto